services:
  - type: web
    name: branchout
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: FLASK_ENV
        value: production
      - key: APP_NAME
        value: BranchOut
      - key: SECRET_KEY
        generateValue: true
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: APP_URL
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: branchout-db
          property: connectionString

databases:
  - name: branchout-db
    plan: free
